language: c
compiler:
    - clang
    - gcc
env:
    - COVERAGE=false
    - COVERAGE=true
sudo: false
addons:
    apt:
        packages:
            - check
            - python-sphinx
script:
    - $COVERAGE && export CC="${CC} -fprofile-arcs -ftest-coverage -O0 -g" || true
    - $COVERAGE && pip install cpp-coveralls || true
    - make all run-tests doc
after_success:
    - $COVERAGE && coveralls --exclude examples --exclude tests --gcov-options '\-lp' || true
