language: c
compiler:
    - clang
    - gcc
install:
    - sudo pip install cpp-coveralls
    - sudo apt-get install -y check
script:
    - if [[ $CC = gcc ]] ; then export CC="${CC} -fprofile-arcs -ftest-coverage -O0 -g" ; endif
    - make all run-tests doc
after_success:
    - coveralls --include 'w*.c' --include wheel.h --gcov-options '\-lp'
