language: c
compiler:
    - clang
    - gcc
env:
    - COVERAGE=false
    - COVERAGE=true
install:
    - $COVERAGE && sudo pip install cpp-coveralls || true
    - sudo apt-get install -y check
script:
    - $COVERAGE && export CC="${CC} -fprofile-arcs -ftest-coverage -O0 -g" || true
    - make all run-tests doc
after_success:
    - $COVERAGE && coveralls --include 'w*.c' --include wheel.h --gcov-options '\-lp' || true
