language: c
compiler:
    - clang
    - gcc
install:
    - sudo apt-get install -y check
    - pip install cpp-coveralls
script:
    - test "$CC" = gcc && export CC="$CC -fprofile-arcs -ftest-coverage -O0 -g"
    - make all run-tests doc
after_success:
    - coveralls --include 'w*.c' --include wheel.h --gcov-options '\-lp'
