#! /bin/bash
set -e

mydir=$(dirname "$0")
python=$(type -P python2)
if [[ -z ${python} ]] ; then
	python=$(type -P python)
fi

if [[ -z ${python} ]] ; then
	echo "Python not installed, skipping test" 1>&2
	exit 0
fi

for file in "${mydir}"/../examples/wcfg-test-??.conf
do
	echo "Validating tnetstring generated for $(basename "${file}")"
	"${mydir}/../examples/wcfg-to-tnetstring" < "${file}" \
		| "${python}" "${mydir}/tnetstrings.py"
done

